### ISSUE TITLE
你好，我使用npm install 下载依赖，项目报错

### ISSUE THREAD

**Issue by JserJser** [jianpiao/tempGL#1]
gypgyp  ERR! ERR! build error 
build error 
gyp ERR!gyp stack  Error: `make` failed with exit code: 2
gypERR!  ERR!stack  Error: `make` failed with exit code: 2
stackgyp     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
 gyp ERR!ERR!  stack     at ChildProcess.emit (events.js:182:13)
stackgyp     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
 gypERR!  stackERR!     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
 stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
gyp ERR! System Darwin 18.0.0
gyp ERR!gyp  SystemERR! Darwin 18.0.0
 command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users//517box/tempGL/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users//517box/tempGL/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gypgyp  ERR!ERR!  cwdcommand /Users//517box/tempGL/node_modules/fsevents
 "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Users//517box/tempGL/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users//517box/tempGL/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64"
gyp gypERR!  ERR!node -v  v10.15.0
cwd /Users//517box/tempGL/node_modules/fsevents
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR!gyp ERR! node-gyp -v v3.8.0
gyp  ERR!not ok  
not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute

**Comment by jianpiao** [comment]
看报错信息开头是build error 打包异常，你是在设备上运行的时候报错的吗，可以尝试删除依赖重新安装依赖，如果是虚拟机安装确保有jdk和配置好环境变量。
